export const initialValues = {
  type: '',
  title: '',
  firstName: '',
  lastName: '',
  imageUrl: '',
  series: '',
  date: '',
  dateOfBirth: '',
  dateOfDeath: '',
  isbn: '',
  translation: '',
  publishing: '',
  numberOfPages: '',
  content: '',
  LClink: '',
  status: '',
  oficialWebsite: '',
};
