export const savedValues = {
  type: '',
  title: 'test',
  firstName: 'test',
  lastName: 'test',
  imageUrl: '',
  series: 'test',
  date: '',
  isbn: '',
  translation: 'test',
  publishing: 'test',
  numberOfPages: '',
  content: 'test',
  LClink: '',
  status: '',
  oficialWebsite: '',
  author: 'test',
  quote: 'test',
};
